### ISSUE TITLE
Messaging prototype

### ISSUE THREAD

**Issue by raphpion** [raphpion/UntitledGameServer#1]
## User story

As a player, I want to be able to connect to the game server, send public messages and private messages to other online players and receive messages in real time.

## Tasks

- [ ] **Create a prototype server that listens for Http and WebSocket connections**
  - [ ] Websocket connection initiation that requires a username
  - [ ] Push user logins and logouts to connected users
  - [ ] Push new public and private messages to connected users

- [ ] **Create a prototype console game client that connects to the server**
  - [ ] `/login {username}` and `/logout` for authentication
  - [ ] `/msg {message}` and `/pm {username} "{message}"` to send public and private messages
  - [ ] Display logins and logouts to console
  - [ ] Display public and private messages to console
